### ISSUE TITLE
About your code

### ISSUE THREAD

**Issue by LiquidAmmonia** [EmanueleCosenza/NN4G#1]

**Comment by LiquidAmmonia** [comment]
Thank you for your implementation, it looks like a lot of work, and I have learned a lot from it. However, I think it is irresponsible to leave your incomplete code in the community like this, I have found more than a dozen bugs in your code, most of them are pretty obvious ones, and I believe you could have solve them before you publish your code.

**Comment by EmanueleCosenza** [comment]
Sorry to hear that. I was very inexperienced with Python and PyTorch when I was working on the project.

However, the code should work on the datasets I provided, can you confirm?
Can you please tell me more about the bugs?
